server:
  port: 8008

spring:
  application:
    name: mt-server-schedule
    #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mt_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: yxq99700
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
eureka:
  instance:
    instance-id: mt-server-schedule
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#sql日志
logging:
  level:
    com:
      mt:
        schedule:
          dao: debug