server:
  port: 9527

spring:
  application:
    name: mt-zuul

eureka:
  instance:
    instance-id: mt-zuul
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

zuul:
  routes:
    mt-server-user:
    # swagger文档会重复扫描下面路径 需要统一一个入口
     #  path: /user2/**
      serviceId: mt-server-user

feign:
  httpclient:
    enabled: true
