spring:
  rabbitmq:
    host: www.conqin.club
    username: conqin
    password: 123456
    listener:
      simple:
        acknowledge-mode: NONE # NONE 表示发送完消息马上从队列中删除掉  manual手动确认消费
    virtual-host: /message_host

  #redis配置
  redis:
    port: 6379
    host: www.conqin.club
    password: 123456
    timeout: 2000
    jedis:
      pool:
        max-active: 10