server:
  port: 8004

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mt.film.entity       #所有entity别名类所在包

spring:
  application:
    name: mt-server-film
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mt_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  main:
   allow-bean-definition-overriding: true
eureka:
  instance:
    instance-id: mt-server-film
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
