##问题: 使用yml时 @value注解无法读取到配置信息
#spring:
#  redis:
#    host: 49.235.240.242
#    port: 6379
#    password: 123456
#    timeout: 30000
##    jedis:
##      pool:
##        max-active: 8
##        max-wait: 30
##        max-idle: 8
##        min-idle: 0
