server:
  port: 8003

spring:
  profiles:
    include: auth
  application:
    name: mt-server-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mt_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    default-property-inclusion: non_null


mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    instance-id: mt-server-user
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


